spring:
  application:
    name: sakila

  datasource:
    url: jdbc:mysql://localhost:33306/sakila
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        cache:
          use_second_level_cache: false
        generate_statistics: true
    open-in-view: true

logging:
  level:
    chan99k.sakila.application: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
        engine:
          internal:
            StatefulPersistenceContext: TRACE
        cache: TRACE
        loader: TRACE
        event:
          internal:
            DefaultLoadEventListener: TRACE
            DefaultInitializeCollectionEventListener: TRACE
        persister:
          entity: TRACE
    web: DEBUG

