version: '3.8'

services:
  mysql:
    image: mysql:8.0.36
    container_name: sakila-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sakila
    ports:
      - "33306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/sakila-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./src/main/resources/sakila-data.sql:/docker-entrypoint-initdb.d/02-data.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data: