version: '3'
services:
  db:
    image: mysql:8.0.36
    container_name: spring-security-mysql
    restart: always
    ports:
      - '43306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d