spring:
  servlet:
    multipart:
      max-file-size: 100MB
  graphql:
    websocket:
      path: graphql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    root: info

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "metrics"